FROM node:20-alpine
WORKDIR /app
COPY frontend/package.json frontend/package-lock.json* ./
RUN npm ci --silent || npm install --silent
COPY frontend .
RUN chmod +x ./entrypoint.sh
EXPOSE 5173
EXPOSE 3001
CMD ["/bin/sh", "./entrypoint.sh"]
